name: Build and Test

on:
  workflow_call:
    inputs:
      force:
        description: run the workflow even if it is skippable
        default: false
        required: false
        type: boolean
  workflow_dispatch:
    inputs:
      force:
        description: run the workflow even if it is skippable
        default: false
        required: false
        type: boolean
  pull_request:
  push:
    branches-ignore:
      - master
      - alpha

jobs:
  build-test:
    name: Build, Lint and Test
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@0f645193c3859845220712632b5106c7f152432f
    with:
      job-title: Build, Lint and Test
      os: '[ "ubuntu-22.04", "windows-latest" ]'
      force: ${{ inputs.force == true }}

  package:
    name: Package
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@0f645193c3859845220712632b5106c7f152432f
    with:
      job-title: Package
      pnpm-commands: '[ "package" ]'
      os: '[ "ubuntu-22.04" ]'
      node-versions: '[ "18" ]'
      artifact-path: dist-jsii
      artifact-name: dist-jsii
      force: ${{ inputs.force == true}}
