name: Build and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - master
      - alpha

jobs:
  build-test:
    name: Build, Lint and Test
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@0f645193c3859845220712632b5106c7f152432f
