name: Build and Test

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      force:
        description: run the workflow even if it is skippable
        default: false
        required: false
        type: boolean
  pull_request:
  push:
    branches-ignore:
      - main
      - alpha

jobs:
  build-test:
    name: Build, Lint and Test
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@4519d724fd3e9b0295f9407d5b48f019d1d43033
    with:
      job-title: Build, Lint and Test
      os: '[ "ubuntu-22.04", "windows-latest" ]'
      force: ${{ inputs.force == true }}

  package:
    name: Package
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@4519d724fd3e9b0295f9407d5b48f019d1d43033
    with:
      job-title: Package
      pnpm-commands: '[ "package" ]'
      os: '[ "ubuntu-22.04" ]'
      node-versions: '[ "18" ]'
      force: ${{ inputs.force == true}}
