name: Release go manually
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: tksst/github-actions-workflows/actions/setup-pnpm-project@4d3055bc0622325eb8d538659de8c78957a73a2a
        with:
          node-version: 18

      - run: pnpm build

      - run: pnpm package

      - name: publish go
        run: pnpm exec publib-golang dist-jsii/go
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GIT_USER_NAME: github-actions[bot]
          GIT_USER_EMAIL: github-actions[bot]@users.noreply.github.com
