name: Release to Maven manually
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: tksst/github-actions-workflows/actions/setup-pnpm-project@6da3b9300d3cc7d7cfb1108c7f5b3783b2a18826
        with:
          node-version: 18

      - run: pnpm build

      - run: pnpm package

      - name: publish to Maven
        run: pnpm exec publib-maven dist-jsii/java
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          MAVEN_GPG_PRIVATE_KEY_PASSPHRASE: ${{ secrets.MAVEN_GPG_PRIVATE_KEY_PASSPHRASE }}
          MAVEN_STAGING_PROFILE_ID: ${{ secrets.MAVEN_STAGING_PROFILE_ID }}
          MAVEN_ENDPOINT: ${{ secrets.MAVEN_ENDPOINT }}
