name: Release to NuGet manually
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: tksst/github-actions-workflows/actions/setup-pnpm-project@4d3055bc0622325eb8d538659de8c78957a73a2a
        with:
          node-version: 18

      - run: pnpm build

      - run: pnpm package

      - name: publish to NuGet
        run: pnpm exec publib-nuget dist-jsii/dotnet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
