name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force:
        description: Force the other language packages to be published
        default: false
        required: false
        type: boolean

concurrency: release

jobs:
  build-test-package:
    uses: ./.github/workflows/build-test.yml

  release:
    needs: build-test-package
    permissions:
      # provenance
      id-token: write
      # create a PR
      contents: write
      pull-requests: write
    runs-on: ubuntu-22.04

    steps:
      - uses: tksst/github-actions-workflows/actions/setup-pnpm-project@4d3055bc0622325eb8d538659de8c78957a73a2a
        with:
          node-version: 18

      - name: build for npm
        run: pnpm build

      - name: Create Release Pull Request or Publish to npm
        id: publish-with-changesets-action
        uses: changesets/action@f13b1baaa620fde937751f5d2c3572b9da32af23 # v1.4.5
        with:
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: make packages
        if: steps.publish-with-changesets-action.outputs.published == 'true' || inputs.force == true
        run: pnpm package

      - name: publish to the other packages
        if: steps.publish-with-changesets-action.outputs.published == 'true' || inputs.force == true
        run: rm -rf dist-jsii/js && pnpm exec publib dist-jsii
        env:
          # Go publish
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          # Java
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          MAVEN_GPG_PRIVATE_KEY_PASSPHRASE: ${{ secrets.MAVEN_GPG_PRIVATE_KEY_PASSPHRASE }}
          MAVEN_STAGING_PROFILE_ID: ${{ secrets.MAVEN_STAGING_PROFILE_ID }}
          MAVEN_ENDPOINT: ${{ secrets.MAVEN_ENDPOINT }}
          # Python
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          # Go
          GIT_USER_NAME: github-actions[bot]
          GIT_USER_EMAIL: github-actions[bot]@users.noreply.github.com
          # dotnet
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
