name: Release
on:
  push:
    branches:
      - master
      - alpha

jobs:
  build-test-package:
    uses: ./.github/workflows/build-test.yml

  release:
    needs: build-test-package
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          # fetch all history
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # tag=v2.2.4

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Release
        env:
          # @semantic-release/github and Go publish
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          # NPM
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Java
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          MAVEN_GPG_PRIVATE_KEY_PASSPHRASE: ${{ secrets.MAVEN_GPG_PRIVATE_KEY_PASSPHRASE }}
          MAVEN_STAGING_PROFILE_ID: ${{ secrets.MAVEN_STAGING_PROFILE_ID }}
          MAVEN_ENDPOINT: ${{ secrets.MAVEN_ENDPOINT }}
          # Python
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          # Go
          GIT_USER_NAME: github-actions[bot]
          GIT_USER_EMAIL: github-actions[bot]@users.noreply.github.com
          # dotnet
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

        run: pnpm exec semantic-release
